/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhir;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class formSeleksi extends javax.swing.JFrame {
    Connection Con;
    ResultSet RsPs;
    Statement stm; 
    private Object[][] dataTable = null; 
    private String[] header = {"Kode Peserta","Nama Peserta","Provinsi","Pendidikan","Usia","IPK","Surat Ket Sehat","SKCK","Email","Telepon"};

    /**
     * Creates new form formSeleksi
     */
    public formSeleksi() {
        initComponents();
        koneksi();
        tblSeleksi();
    }
    
    private void koneksi(){
        try {
            KoneksiMysql kon = new KoneksiMysql ("localhost", "root", "", "pkkp");
            Con = kon.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void tblSeleksi(){
        DefaultTableModel tb= new DefaultTableModel();
        tb.addColumn("Kode Peserta");
        tb.addColumn("Nama Peserta");
        tb.addColumn("Provinsi");
        tb.addColumn("Pendidikan");
        tb.addColumn("usia");
        tb.addColumn("ipk");
        tb.addColumn("Surat Keterangan Sehat");
        tb.addColumn("SKCK");
        tb.addColumn("Email");
        tb.addColumn("No Telepon");
        tblSeleksi.setModel(tb);
        try{
            stm  = Con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            RsPs = stm.executeQuery("select * from tblpeserta");
            ResultSetMetaData meta = RsPs.getMetaData();
            int col = meta.getColumnCount();
            int baris = 0;
            while (RsPs.next()) {
                baris = RsPs.getRow();
            }
            dataTable = new Object [baris] [col];
            int x = 0;
            RsPs.beforeFirst();
            while(RsPs.next()){
                dataTable[x][0] = RsPs.getString("kd_peserta");
                dataTable[x][1] = RsPs.getString("nm_peserta");
                dataTable[x][2] = RsPs.getString("Provinsi");
                dataTable[x][3] = RsPs.getString("Pendidikan");
                dataTable[x][4] = RsPs.getString("usia");
                dataTable[x][5] = RsPs.getString("ipk");
                dataTable[x][6] = RsPs.getString("surat_ket_sht");
                dataTable[x][7] = RsPs.getString("skck");
                dataTable[x][8] = RsPs.getString("email");
                dataTable[x][9] = RsPs.getString("no_telp");
                x++;
            }
            tblSeleksi.setModel(new DefaultTableModel(dataTable, header));
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeleksi = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSeleksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSeleksi);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKeluar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formSeleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formSeleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formSeleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formSeleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formSeleksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSeleksi;
    // End of variables declaration//GEN-END:variables
}
